Fix Issue: https://github.com/AngleSharp/AngleSharp/issues/1147
AngleSharp/AngleSharp pull request #1148
Opened 2023-11-15 08:54 UTC by zukarusan

# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## Description

Fix the issue of not setting up `Start` and `End` property after one of both is explicitly given. The core fix is to modify `CompareTo` function according to the described algorithm from https://dom.spec.whatwg.org/#boundary-points Additionally, added more operator functions with overridden `Equals` & `GetHasCode` functions as well.

Also, the test case for this issue is added in Library/Range.cs.

2023-11-15 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AngleSharp/AngleSharp?pullRequest=1148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AngleSharp/AngleSharp?pullRequest=1148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AngleSharp/AngleSharp?pullRequest=1148) it.</sub>

2023-11-15 12:44 UTC, FlorianRappl approved these changes
Great - yes this looks good to me. I will need to look into the W3C proposed algorithm, but from a first glance / the test it works wonderfully.

Much appreciated!

2023-11-16 08:02 UTC, FlorianRappl requested changes

2023-11-16 08:02 UTC, FlorianRappl commented on src/AngleSharp/Dom/INode.cs
> +        Int32 NodeLength { get; }
Please remove this. It would be a breaking change and usually such algorithms are rather implemented as helper functions.

In addition most things on the INode are only there if there is an official API for it - so unless there is a DomName its better to not put it on the INode.

2023-11-16 16:23 UTC, zukarusan commented on src/AngleSharp/Dom/INode.cs
> +        Int32 NodeLength { get; }
Hi @FlorianRappl 
Thank you for your kind review

I apologize for my bad habit of pushing into my local without realizing it's auto-creating pull requests.

It's now reset with another commit

2023-11-16 19:08 UTC, FlorianRappl approved these changes
LGTM - this superb! Thanks for giving `IRange` the time & love it deserves. Much appreciated!

2023-11-16 19:08 UTC, FlorianRappl commented on src/AngleSharp/Dom/INode.cs
> +        Int32 NodeLength { get; }
All fine - thanks for putting in the effort. Went over the tests, yes, matches the desired behavior & spec. Well done!

2023-11-16 19:45 UTC, merged