Added an optional callback OnToken
AngleSharp/AngleSharp pull request #1153
Opened 2023-12-03 20:46 UTC by schaakverslaafd

# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [x] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly (NOT YET)
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## Description

Added an OnToken event to the htmlParser raised when a new html token is consumed. This event passes the html token and a range in the source text corresponding to the token.
I didn't update documentation (yet). Provided this pull request to discuss issue #754.

2023-12-03 22:17 UTC, FlorianRappl commented
Alright we definitely need to see two benchmarks here (on a large HTML document):

1. Old code (no modification)
2. With `OnToken` (does not need to be provided; the performance should roughly remain the same for the case that no `OnToken` callback was provided)

Could this be done? Thanks for your efforts!

2024-03-15 22:47 UTC, schaakverslaafd commented
Hi,

Sorry for a late reponse.

Two benchmarks from parsing page.html from the benchmark project.

Benchmark for old code
![Benchmark-OldCode](https://github.com/AngleSharp/AngleSharp/assets/540201/a15395ca-5c94-4077-84fe-4c5fde91114d)

Benchmark with OnToken
![BenchMark-OnToken](https://github.com/AngleSharp/AngleSharp/assets/540201/a78e06a1-ef0c-4520-ba78-55bd7318f4c5)

```
using System.IO;
using AngleSharp.Html.Parser;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;

namespace AngleSharp.Benchmarks
{
    [MemoryDiagnoser, GroupBenchmarksBy(BenchmarkLogicalGroupRule.ByParams), ShortRunJob]
    public class OnTokenBenchmark
    {
        private static readonly HtmlParser angleSharpParser = new HtmlParser();
        private string pageContent = "";

        [GlobalSetup]
        public void GlobalSetup()
        {
            pageContent = File.ReadAllText("page.html");
        }

        [Benchmark]
        public void AngleSharp()
        {
            angleSharpParser.ParseDocument(pageContent);
        }
    }
}
```

2024-03-16 13:01 UTC, FlorianRappl commented
Great thanks for the efforts @schaakverslaafd - can you update your branch (sync with `devel`)? Then we are ready to merge!

2024-03-17 09:05 UTC, schaakverslaafd commented
Great!
I merged the branches. My editor messed up the spacing a bit. Let me know if that's an issue.

(The original solution had to be changed a bit because StructHtmlToken is passed by ref. New benchmarks did not show a significant difference.)

2024-03-17 23:21 UTC, FlorianRappl requested changes

2024-03-17 23:21 UTC, FlorianRappl commented on src/AngleSharp/Html/Parser/HtmlTokenizer.cs
> +                            c = SkipSpaces();
Yeah sorry the space change makes the PR quite unreadable.

Can you please undo these space changes? Thanks a lot.

2024-03-18 19:21 UTC, schaakverslaafd commented
Alright! The space change are removed.

2024-03-18 21:59 UTC, FlorianRappl approved these changes
LGTM - thanks for all your efforts 🚀 !

2024-03-18 22:50 UTC, merged