proper user name for CLA
AngleSharp/AngleSharp pull request #1159
Opened 2023-12-24 15:19 UTC by dv00d00

# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [ ] I have read the **CONTRIBUTING** document
- [ ] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## Description

[Place a meaningful description here.]

2023-12-24 15:22 UTC, dv00d00 commented
commit history: https://github.com/AngleSharp/AngleSharp/pull/1157

2023-12-24 21:39 UTC, dv00d00 commented
Several benchmarks from the readonly repo

|            Method |      Mean |      Error |    StdDev |   Gen0 | Allocated |
|------------------ |----------:|-----------:|----------:|-------:|----------:|
|         Selectors | 149.31 us |   3.008 us |  0.165 us | 2.1973 |   20312 B |
| SelectorsReadonly |  82.09 us | 239.225 us | 13.113 us |      - |     184 B |


|           Method |      UrlTest |            Mean |          Error |        StdDev | Ratio | RatioSD |       Gen0 |       Gen1 |      Gen2 |    Allocated | Alloc Ratio |
|----------------- |------------- |----------------:|---------------:|--------------:|------:|--------:|-----------:|-----------:|----------:|-------------:|------------:|
| ReadonlyFiltered |          163 |     8,639.65 us |     287.825 us |     15.777 us |  5.76 |    0.14 |   125.0000 |    62.5000 |         - |   1048.09 KB |        0.66 |
|         Readonly |          163 |       989.35 us |      10.491 us |      0.575 us |  0.66 |    0.01 |    15.6250 |     1.9531 |         - |    128.96 KB |        0.08 |
|          Default |          163 |     1,501.26 us |     604.591 us |     33.140 us |  1.00 |    0.00 |   146.4844 |    70.3125 |    3.9063 |   1589.53 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |       360.cn |     1,605.62 us |      58.646 us |      3.215 us |  0.34 |    0.00 |    41.0156 |     9.7656 |         - |    335.28 KB |        0.17 |
|         Readonly |       360.cn |     1,909.26 us |      26.295 us |      1.441 us |  0.40 |    0.00 |    74.2188 |    52.7344 |         - |    615.67 KB |        0.31 |
|          Default |       360.cn |     4,738.94 us |     280.025 us |     15.349 us |  1.00 |    0.00 |   234.3750 |   179.6875 |         - |   1957.41 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |   aliexpress |     1,785.37 us |      94.266 us |      5.167 us |  0.60 |    0.00 |     9.7656 |          - |         - |     83.72 KB |        0.02 |
|         Readonly |   aliexpress |     1,776.90 us |      12.890 us |      0.707 us |  0.59 |    0.00 |    23.4375 |     5.8594 |         - |    197.97 KB |        0.05 |
|          Default |   aliexpress |     2,992.60 us |     391.970 us |     21.485 us |  1.00 |    0.00 |   175.7813 |   132.8125 |   39.0625 |   4143.11 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |          ask |       862.16 us |     159.518 us |      8.744 us |  0.34 |    0.00 |    12.6953 |     2.9297 |         - |    108.57 KB |        0.07 |
|         Readonly |          ask |     1,012.69 us |     225.182 us |     12.343 us |  0.39 |    0.01 |    31.2500 |    13.6719 |         - |    256.13 KB |        0.16 |
|          Default |          ask |     2,568.30 us |     220.315 us |     12.076 us |  1.00 |    0.00 |   148.4375 |    97.6563 |         - |   1594.44 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered | en.wikipedia |     9,831.21 us |   1,203.639 us |     65.976 us |  0.41 |    0.05 |   250.0000 |   203.1250 |         - |   2121.45 KB |        0.22 |
|         Readonly | en.wikipedia |    11,430.68 us |   3,603.529 us |    197.522 us |  0.47 |    0.07 |   343.7500 |   296.8750 |         - |    2888.5 KB |        0.30 |
|          Default | en.wikipedia |    24,450.85 us |  64,685.425 us |  3,545.626 us |  1.00 |    0.00 |   843.7500 |   750.0000 |         - |   9586.91 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |   html5rocks |       934.96 us |      26.581 us |      1.457 us |  0.41 |    0.00 |    14.6484 |     3.9063 |         - |    126.23 KB |        0.13 |
|         Readonly |   html5rocks |     1,190.36 us |      89.499 us |      4.906 us |  0.52 |    0.00 |    37.1094 |    17.5781 |         - |    308.81 KB |        0.32 |
|          Default |   html5rocks |     2,278.60 us |     421.204 us |     23.088 us |  1.00 |    0.00 |   113.2813 |    66.4063 |         - |    954.16 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |         imdb |    27,657.84 us |  27,089.162 us |  1,484.848 us |  1.76 |    0.10 |    31.2500 |          - |         - |    389.12 KB |        0.03 |
|         Readonly |         imdb |    17,794.53 us |   7,849.207 us |    430.241 us |  1.13 |    0.03 |   125.0000 |    93.7500 |         - |    1173.3 KB |        0.09 |
|          Default |         imdb |    15,739.83 us |   1,770.787 us |     97.063 us |  1.00 |    0.00 |   718.7500 |   593.7500 |  125.0000 |   13314.1 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |   kickass.to |        97.54 us |       2.348 us |      0.129 us |  0.21 |    0.00 |     0.9766 |          - |         - |      8.83 KB |        0.02 |
|         Readonly |   kickass.to |       105.02 us |       7.883 us |      0.432 us |  0.23 |    0.00 |     2.6855 |     0.1221 |         - |     21.97 KB |        0.05 |
|          Default |   kickass.to |       461.87 us |     146.261 us |      8.017 us |  1.00 |    0.00 |    49.8047 |    14.6484 |         - |    411.96 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |      mail.ru |     3,726.30 us |     628.333 us |     34.441 us |  0.79 |    0.01 |    19.5313 |     3.9063 |         - |     186.4 KB |        0.04 |
|         Readonly |      mail.ru |     3,408.30 us |     454.148 us |     24.893 us |  0.72 |    0.00 |    54.6875 |    27.3438 |         - |    452.39 KB |        0.11 |
|          Default |      mail.ru |     4,735.60 us |     250.814 us |     13.748 us |  1.00 |    0.00 |   281.2500 |   250.0000 |   31.2500 |   4291.73 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |          nbc |     8,680.58 us |     110.158 us |      6.038 us |  0.31 |    0.00 |   125.0000 |    93.7500 |         - |   1048.08 KB |        0.05 |
|         Readonly |          nbc |    10,709.10 us |     433.334 us |     23.752 us |  0.38 |    0.00 |   265.6250 |   218.7500 |         - |   2284.76 KB |        0.11 |
|          Default |          nbc |    28,370.92 us |   6,001.273 us |    328.950 us |  1.00 |    0.00 |  1375.0000 |  1218.7500 |  218.7500 |   19876.1 KB |        1.00 |
|                  |              |                 |                |               |       |         |            |            |           |              |             |
| ReadonlyFiltered |       neobux |        40.17 us |       2.254 us |      0.124 us |  0.22 |    0.01 |     1.1597 |          - |         - |      9.51 KB |        0.17 |
|         Readonly |       neobux |        44.07 us |       0.988 us |      0.054 us |  0.24 |    0.01 |     1.9531 |     0.0610 |         - |     15.98 KB |        0.29 |
|          Default |       neobux |       181.12 us |     156.882 u [...]

2023-12-25 17:17 UTC, dv00d00 commented on src/AngleSharp/Dom/Internal/Document.cs
> +                    throw new InvalidOperationException();
not sure about this one

2023-12-25 17:19 UTC, dv00d00 commented on src/AngleSharp/Dom/Url.cs
> -            var chars = new Char[length];
probably worth adding failsafe check for wrong length, don't know tbh

2023-12-25 19:24 UTC, FlorianRappl requested changes
I am thinking now for a couple of days what to do with this PR.

As already mentioned; any change *cannot* be breaking - but this PR is full of breaking changes.

If you are unsure what is breaking and what not - build / compile a project with the latest release then just swap the anglesharp.dll with the result of your changes. If the program still runs its non-breaking; otherwise something in the API or even the ABI (IL) broke between the latest release and the given build.

That being written I am totally fine with adding new services and extending the whole model, but we cannot change / alter (public) interfaces at all.

Do you see a way forward to have this non-breaking?

2023-12-25 19:24 UTC, FlorianRappl commented on src/AngleSharp.Core.Tests/TestExtensions.cs
> +    using Text;
What's this / why needed?

2023-12-25 19:24 UTC, FlorianRappl commented on src/AngleSharp/Configuration.cs
> +                Creator<IHtmlElementConstructionFactory>(ctx => new HtmlDomConstructionFactory(ctx)),
What if this is not given? Is it still operational? Because if not, this is breaking - it should just work with existing configurations, which might not have this one.

2023-12-25 19:24 UTC, FlorianRappl commented on src/AngleSharp.Core.Tests/Mocks/MarkdownDocument.cs
>              : base(context, source)
Is this change required? It should not be, otherwise is breaking.

2023-12-25 19:24 UTC, FlorianRappl commented on src/AngleSharp.Core.Tests/Mocks/MockEntityProvider.cs
> +        public String GetSymbol(StringOrMemory name)
Required? It should not be - otherwise its breaking.

2023-12-25 19:24 UTC, FlorianRappl commented on src/AngleSharp/Common/BaseTokenizer.cs
> +        public BaseTokenizer(IReadOnlyTextSource source)
This is breaking - it should not be.

2023-12-25 19:24 UTC, FlorianRappl commented on src/AngleSharp/Common/BaseTokenizer.cs
> +        protected IMutableCharBuffer StringBuffer => _buffer;
This is breaking - we need to find a way to make this non-breaking.

2023-12-25 20:06 UTC, dv00d00 commented on src/AngleSharp/Configuration.cs
> +                Creator<IHtmlElementConstructionFactory>(ctx => new HtmlDomConstructionFactory(ctx)),
The current implementation of the HtmlDomBuilder requires this service to be present in the context, easy to fix with the fallback to default implementation

2023-12-25 20:20 UTC, dv00d00 commented on src/AngleSharp.Core.Tests/Mocks/MarkdownDocument.cs
>              : base(context, source)
TextSource implements IReadOnlyTextSource, can I add new constructor here?

2023-12-25 20:23 UTC, dv00d00 commented
So just to be sure, we are aiming to produce binary compatible incremental update. E.g. new compiled dll should be binary compatible with the old one.

I have a feeling that this PR is almost compile time compatible though.

I've added new interfaces to INode and friends, it will break any custom implementations. If we are ok with this I believe I will be able to fix other stuff.

btw would bumping version to something like 1.1.0 lift binary compatibility requirement?

2023-12-25 20:27 UTC, dv00d00 commented on src/AngleSharp.Core.Tests/TestExtensions.cs
> +    using Text;
cheap way to cover PrefetchedTextSource with unit tests

`if (TestRuntime.UserPrefetchedTextSource)
            {
                var textSource = new PrefetchedTextSource(sourceCode.AsMemory());
                return htmlParser.ParseDocument(textSource);
            }
            else
            {
                return htmlParser.ParseDocument(sourceCode);
            }`

2023-12-25 21:56 UTC, dv00d00 commented on src/AngleSharp/Html/Parser/Tokens/Struct/MemoryHtmlAttributeToken.cs
> +public readonly struct MemoryHtmlAttributeToken
Should it be public?

2023-12-25 22:18 UTC, dv00d00 commented
Finished the first pass to fix backward compat, looks promising, tests are green

2023-12-25 22:19 UTC, dv00d00 commented
Will take another look tomorrow as well, also would appreciate naming advices

2023-12-25 22:21 UTC, dv00d00 commented on src/AngleSharp.Core.Tests/Mocks/MockEntityProvider.cs
> +        public String GetSymbol(StringOrMemory name)
fixed via new interface, name is terrible though

2023-12-25 23:15 UTC, FlorianRappl commented on src/AngleSharp.Core.Tests/TestExtensions.cs
> +    using Text;
Ok in the previous commit (when I made the comment) only the using statement was present; the additional block not.

I think this refers to `AngleSharp.Text`- can we make the usings always FQ? Thanks!

2023-12-25 23:16 UTC, FlorianRappl commented on src/AngleSharp.Core.Tests/Mocks/MarkdownDocument.cs
>              : base(context, source)
Yes, but keep in mind that `TextSource` is not allowed to have breaking changes. Therefore, if you require `MarkdownDocument` to change this is an indicator that `Document` has a breaking change. So it needs to be changed anyway.

2023-12-25 23:19 UTC, FlorianRappl commented
> btw would bumping version to something like 1.1.0 lift binary compatibility requirement?

Unfortunately no. Any breaking change (API or ABI) needs to be a 2.0.0. The 1.1.0 would indicate a massive new feature (which this is, so I'd anyway put this on a 1.1.0 to indicate something new inside).

This is maybe debatable, however, from my expectation as a user as a non-breaking (i.e., 1.x) release I'd expect binary compatibility, too, as otherwise re-compilation is required. Surely, in most practical cases the update would come with a re-compilation - most people are not "hot-patching" their dependencies, but you never know (and personally I was involved in projects that did hot patching, at least with smoke tests, in the past).

2023-12-25 23:20 UTC, FlorianRappl commented on src/AngleSharp/Html/Parser/Tokens/Struct/MemoryHtmlAttributeToken.cs
> +public readonly struct MemoryHtmlAttributeToken
Good question. I'll need to think about it.

2023-12-26 08:18 UTC, dv00d00 commented
I've just replaced compiled AngleSharp.dll for my web app, and old execution paths which were using AngleSharp are still working

2023-12-26 08:32 UTC, dv00d00 commented on src/AngleSharp.Core.Tests/TestExtensions.cs
> +    using Text;
On the second thought this is not so cheap, IDE experience is bad, CI build runs test suit 2x times. Another option is to maybe create a base class for test fixture using this method and override it for `PrefetchedTextSource` use

2023-12-26 08:41 UTC, dv00d00 commented on src/AngleSharp.Core.Tests/TestExtensions.cs
> +    using Text;
There are 200+ usages, I can update all tests in this or another pr, adding extra 80 files would make it PR even bigger ...

2023-12-26 10:43 UTC, dv00d00 commented
I'll take a look at broken test, meanwhile here is a hacked api diff for netstandard

![image](https://github.com/AngleSharp/AngleSharp/assets/1162823/0edbebfe-56b8-4c23-885c-f24ea440288c)

281 Additions 0 Removals hopefully it will make review easier

It's using https://www.fuget.org/ to render api diff

2023-12-26 10:57 UTC, FlorianRappl commented
Great thanks for the picture - green is good :)

Yes, I think we are (getting) ready to merge this one.

Regarding naming; especially for the `IEntityResolver` I also don't have a better name. Actually, having this in the interface would be the best (obviously), but yeah - breaking is not what we want (at this point). Maybe let's go here for something like `IExtendedEntityResolver`.

2023-12-26 10:58 UTC, FlorianRappl commented on src/AngleSharp/Html/Parser/Tokens/Struct/MemoryHtmlAttributeToken.cs
> +public readonly struct MemoryHtmlAttributeToken
Even though the other tokens are public I am not sure if this one should be. Initially, the others have been internal, but that has shifted when access to the tokenizer / retrieving the original token was made possible. Right now I am not sure if we need to have this public - I'd like to keep it internal if its not really needed on the outside API (prevents potential breaking changes in the future).

2023-12-26 11:38 UTC, dv00d00 commented
Is there a reason we are not running unit tests against full framework? CI?

2023-12-27 10:16 UTC, dv00d00 commented
I've ran benchmarks with code from devel and merged results

|               Method |              UrlTest |            Mean |          Error |        StdDev |       Gen0 |       Gen1 |      Gen2 |    Allocated |
|--------------------- |--------------------- |----------------:|---------------:|--------------:|-----------:|-----------:|----------:|-------------:|
|         AngleSharpOG |                  163 |     1,734.06 us |     126.159 us |      6.915 us |   199.2188 |   128.9063 |   66.4063 |   1648.25 KB |
|           AngleSharp |                  163 |     2,197.02 us |     163.035 us |      8.937 us |   199.2188 |   121.0938 |   66.4063 |   1413.85 KB |
| AngleSharpPrefetched |                  163 |     1,921.66 us |     126.982 us |      6.960 us |   144.5313 |    48.8281 |         - |   1189.57 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |               360.cn |     4,990.96 us |     930.732 us |     51.017 us |   304.6875 |   148.4375 |   46.8750 |   2640.82 KB |
|           AngleSharp |               360.cn |     6,437.64 us |     635.195 us |     34.817 us |   242.1875 |    93.7500 |   46.8750 |   2121.56 KB |
| AngleSharpPrefetched |               360.cn |     6,063.16 us |     857.046 us |     46.978 us |   234.3750 |    85.9375 |         - |   1935.44 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |           aliexpress |     3,787.66 us |     316.345 us |     17.340 us |   656.2500 |   574.2188 |  500.0000 |   3688.12 KB |
|           AngleSharp |           aliexpress |     5,111.89 us |     358.648 us |     19.659 us |   632.8125 |   570.3125 |  500.0000 |   3563.19 KB |
| AngleSharpPrefetched |           aliexpress |     4,698.96 us |     437.443 us |     23.978 us |   406.2500 |   359.3750 |  328.1250 |   2001.12 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |               amazon |       210.02 us |      21.273 us |      1.166 us |    15.1367 |     2.6855 |         - |    124.95 KB |
|           AngleSharp |               amazon |       289.01 us |      54.452 us |      2.985 us |    13.1836 |     2.4414 |         - |    107.74 KB |
| AngleSharpPrefetched |               amazon |       271.86 us |      32.556 us |      1.785 us |    10.7422 |     1.4648 |         - |     90.52 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |                  ask |     2,863.56 us |     646.669 us |     35.446 us |   179.6875 |   109.3750 |   54.6875 |    1570.1 KB |
|           AngleSharp |                  ask |     3,575.20 us |     452.848 us |     24.822 us |   164.0625 |   109.3750 |   54.6875 |   1403.14 KB |
| AngleSharpPrefetched |                  ask |     3,400.26 us |     132.460 us |      7.261 us |   140.6250 |    58.5938 |         - |   1160.16 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |                baidu |     4,880.14 us |     420.751 us |     23.063 us |   718.7500 |   640.6250 |  531.2500 |   3756.75 KB |
|           AngleSharp |                baidu |     6,516.32 us |   1,289.760 us |     70.696 us |   718.7500 |   625.0000 |  539.0625 |   3651.38 KB |
| AngleSharpPrefetched |                baidu |     5,891.28 us |   1,590.579 us |     87.185 us |   234.3750 |   187.5000 |  132.8125 |   1352.77 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |                 bing |     1,853.07 us |     245.318 us |     13.447 us |   109.3750 |   109.3750 |  109.3750 |   1203.07 KB |
|           AngleSharp |                 bing |     2,414.16 us |     153.281 us |      8.402 us |   109.3750 |   109.3750 |  109.3750 |   1121.83 KB |
| AngleSharpPrefetched |                 bing |     2,187.19 us |     188.438 us |     10.329 us |    82.0313 |    50.7813 |   27.3438 |    619.91 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |             blogspot |       120.04 us |       6.541 us |      0.359 us |     9.0332 |     0.9766 |         - |     75.77 KB |
|           AngleSharp |             blogspot |       160.52 us |      22.302 us |      1.222 us |     8.3008 |     0.9766 |         - |     69.34 KB |
| AngleSharpPrefetched |             blogspot |       150.39 us |      18.165 us |      0.996 us |     6.3477 |     0.4883 |         - |     52.23 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |          codeproject |     2,432.52 us |     134.241 us |      7.358 us |   207.0313 |    97.6563 |   50.7813 |   1570.38 KB |
|           AngleSharp |          codeproject |     3,095.52 us |     376.893 us |     20.659 us |   156.2500 |   101.5625 |   50.7813 |   1417.07 KB |
| AngleSharpPrefetched |          codeproject |     2,777.97 us |     278.682 us |     15.275 us |   101.5625 |    31.2500 |         - |    861.91 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |                 ebay |    12,002.92 us |   1,748.293 us |     95.830 us |   921.8750 |   765.6250 |  468.7500 |   7360.37 KB |
|           AngleSharp |                 ebay |    15,782.95 us |     886.385 us |     48.586 us |   843.7500 |   656.2500 |  468.7500 |    6965.5 KB |
| AngleSharpPrefetched |                 ebay |    17,323.81 us |  12,756.773 us |    699.242 us |   593.7500 |   531.2500 |  312.5000 |   4438.98 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |         en.wikipedia |    25,173.94 us |   8,703.671 us |   4 77.078 us |  1406.2500 |   843.7500 |  312.5000 |  10556.91 KB |
|           AngleSharp |         en.wikipedia |    28,785.97 us |  11,424.764 us |    626.230 us |  1125.0000 |   718.7500 |  281.2500 |   8235.11 KB |
| AngleSharpPrefetched |         en.wikipedia |    27,120.25 us |   4,863.721 us |    266.597 us |   812.5000 |   406.2500 |         - |    6843.3 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |               flickr |     8,518.18 us |   1,026.690 us |     56.276 us |  1234.3750 |  1140.6250 |  984.3750 |   6645.53 KB |
|           AngleSharp |               flickr |    10,923.10 us |     543.333 us |     29.782 us |  1203.1250 |  1125.0000 |  984.3750 |   6441.84 KB |
| AngleSharpPrefetched |               flickr |    10,955.22 us |     472.960 us |     25.925 us |   453.1250 |   390.6250 |  312.5000 |   3601.72 KB |
|                      |                      |                 |                |               |            |            |           |              |
|         AngleSharpOG |        florian-rappl |       501.11 us |      31.497 us |      1.726 us |    39.0625 |    11.7188 |         - |    326.62 KB |
|           AngleSharp |        florian-rappl |       700.18 us |     218.125 us |     11.956 us |    32.2266 |     4.8828 |         - |    264.11 KB |
| AngleSharpPrefetched |        flo [...]

2023-12-27 10:21 UTC, dv00d00 commented
CPU is generally slower, but partly it is due to delayed cost, I believe that cpu time spent on GC will be comparable to the slowdown, as w3 test shown. That said, I'll take a look and maybe try to improve it a bit

2023-12-27 16:27 UTC, FlorianRappl commented
> Is there a reason we are not running unit tests against full framework? CI?

Full framework = .NET 4.8 or older? These are not supported on the Linux machine and I'd say quite unnecessary. Do you think something else should come out there?

2023-12-27 18:59 UTC, dv00d00 commented
I want to try devirtualization trick, most of slowdown due to virtual calls in tokenizer

2023-12-29 01:25 UTC, dv00d00 commented
Latest change with attribute names reuse had a huge impact for nytimes test, probably true for all other large html sources
Here are results from latest coomit
|     Method |              UrlTest |          Mean |         Error |      StdDev |      Gen0 |      Gen1 |     Gen2 |   Allocated |
|----------- |--------------------- |--------------:|--------------:|------------:|----------:|----------:|---------:|------------:|
| AngleSharp |                    ? |  3,255.582 us |   230.8826 us |  12.6555 us |  226.5625 |  136.7188 |  50.7813 |  3627.73 KB |
|  ArrayPool |                    ? |            NA |            NA |          NA |        NA |        NA |       NA |          NA |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |                  163 | 16,004.835 us | 3,623.2878 us | 198.6046 us | 1125.0000 | 1000.0000 |  31.2500 | 10262.17 KB |
|  ArrayPool |                  163 | 17,418.050 us | 1,064.7283 us |  58.3613 us | 1187.5000 | 1000.0000 |  93.7500 |  8990.58 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |               360.cn |  4,723.179 us |   295.0629 us |  16.1734 us |  226.5625 |  156.2500 |        - |  2053.03 KB |
|  ArrayPool |               360.cn |  4,789.097 us |   641.2628 us |  35.1498 us |  226.5625 |  140.6250 |        - |  1866.98 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |           aliexpress |  2,882.046 us |   134.6753 us |   7.3820 us |  183.5938 |  113.2813 |  46.8750 |   3545.2 KB |
|  ArrayPool |           aliexpress |  2,816.141 us |   116.6017 us |   6.3913 us |   97.6563 |   50.7813 |  23.4375 |  1983.47 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |               amazon |    203.386 us |    15.9511 us |   0.8743 us |   12.6953 |    2.1973 |        - |   105.53 KB |
|  ArrayPool |               amazon |    204.365 us |    10.6257 us |   0.5824 us |   10.7422 |    1.7090 |        - |     88.3 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |                  ask |  2,726.162 us | 8,502.4554 us | 466.0483 us |  144.5313 |   58.5938 |        - |  1380.95 KB |
|  ArrayPool |                  ask |  2,515.940 us |   148.7589 us |   8.1540 us |  136.7188 |   54.6875 |        - |  1136.15 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |                baidu |  3,242.987 us |   330.6151 us |  18.1221 us |  214.8438 |  113.2813 |  39.0625 |  3627.64 KB |
|  ArrayPool |                baidu |  3,262.517 us |   689.9703 us |  37.8196 us |  109.3750 |   54.6875 |   7.8125 |  1333.33 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |                 bing |  1,449.624 us |    38.9917 us |   2.1373 us |   95.7031 |   37.1094 |   3.9063 |  1108.98 KB |
|  ArrayPool |                 bing |  1,465.670 us |    11.9394 us |   0.6544 us |   62.5000 |   23.4375 |        - |   605.53 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |             blogspot |    111.794 us |    11.0361 us |   0.6049 us |    8.3008 |    0.8545 |        - |    68.45 KB |
|  ArrayPool |             blogspot |    112.280 us |    14.1229 us |   0.7741 us |    6.2256 |    0.4883 |        - |    51.35 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |          codeproject |  2,024.790 us |   123.9784 us |   6.7957 us |  148.4375 |   58.5938 |        - |  1395.29 KB |
|  ArrayPool |          codeproject |  1,963.575 us |   108.8248 us |   5.9651 us |  101.5625 |   39.0625 |        - |   838.22 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |                 ebay |  9,146.410 us | 1,557.5319 us |  85.3736 us |  437.5000 |  343.7500 |  62.5000 |  6735.12 KB |
|  ArrayPool |                 ebay |  8,941.050 us | 1,158.8375 us |  63.5198 us |  312.5000 |  218.7500 |  31.2500 |  4269.37 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |         en.wikipedia | 19,725.765 us | 2,115.0640 us | 115.9338 us |  812.5000 |  718.7500 |        - |   8019.4 KB |
|  ArrayPool |         en.wikipedia | 19,727.080 us | 3,841.5913 us | 210.5706 us |  781.2500 |  687.5000 |        - |  6628.31 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |               flickr |  6,001.456 us |    23.1162 us |   1.2671 us |  335.9375 |  250.0000 | 109.3750 |  6416.46 KB |
|  ArrayPool |               flickr |  6,011.006 us |   304.4807 us |  16.6896 us |  187.5000 |  132.8125 |  46.8750 |   3577.6 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |        florian-rappl |    506.378 us |    20.2302 us |   1.1089 us |   31.2500 |    8.7891 |        - |   256.12 KB |
|  ArrayPool |        florian-rappl |    505.721 us |    11.7605 us |   0.6446 us |   27.3438 |    6.8359 |        - |    230.2 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |              godaddy |     11.416 us |     0.4051 us |   0.0222 us |    1.8311 |    0.0610 |        - |    14.97 KB |
|  ArrayPool |              godaddy |     10.843 us |     1.2598 us |   0.0691 us |    1.0834 |    0.0153 |        - |     8.88 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |               google |  1,757.260 us |    49.1503 us |   2.6941 us |  113.2813 |   64.4531 |  42.9688 |  2860.86 KB |
|  ArrayPool |               google |  1,813.880 us |   204.4850 us |  11.2085 us |   42.9688 |   27.3438 |  23.4375 |  1403.02 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |           html5rocks |  2,241.766 us |   178.9140 us |   9.8069 us |  109.3750 |   54.6875 |        - |     1077 KB |
|  ArrayPool |           html5rocks |  2,276.575 us |   241.5424 us |  13.2398 us |  105.4688 |   46.8750 |        - |   881.67 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |            html5test |    339.331 us |    12.3816 us |   0.6787 us |   31.2500 |    8.7891 |        - |   258.86 KB |
|  ArrayPool |            html5test |    335.953 us |    63.9075 us |   3.5030 us |   19.0430 |    4.3945 |        - |   155.64 KB |
|            |                      |               |               |             |           |           |          |             |
| AngleSharp |       huffingtonpost | 13,924.639 us | 2,486.6950 us | 136.3041 us |  609.3750 |  437.5000 |  31.2500 |  6910.79 KB |
|  ArrayPool |       huffingtonpost | 14,350.297 us |   434.2001 us |  23.8000 us |  515.6250 |  437.5000 |        - |  4685.65 KB |
|            |                      |               |               |             |           |           |          |         [...]

2023-12-29 01:49 UTC, dv00d00 commented
same test files on the 1.0.7 repo

|       Method |              UrlTest |          Mean |          Error |      StdDev |      Gen0 |      Gen1 |     Gen2 |   Allocated |
|------------- |--------------------- |--------------:|---------------:|------------:|----------:|----------:|---------:|------------:|
| AngleSharpOG |                    ? |  3,192.139 us |    432.6821 us |  23.7168 us |  230.4688 |  144.5313 |  39.0625 |  3745.19 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                  163 |  1,420.827 us |     10.3925 us |   0.5696 us |  144.5313 |   52.7344 |   3.9063 |  1367.38 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |               360.cn |  4,143.407 us |    203.0197 us |  11.1282 us |  296.8750 |  203.1250 |        - |  2618.47 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |           aliexpress |  2,805.583 us |  1,676.2270 us |  91.8797 us |  226.5625 |  136.7188 |  74.2188 |  3685.72 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |               amazon |    180.738 us |     18.2804 us |   1.0020 us |   15.1367 |    2.9297 |        - |   124.13 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                  ask |  2,241.659 us |    350.5017 us |  19.2122 us |  167.9688 |   78.1250 |        - |  1562.54 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                baidu |  3,044.669 us |    203.4233 us |  11.1503 us |  261.7188 |  171.8750 |  70.3125 |  3745.42 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                 bing |  1,267.351 us |     50.5687 us |   2.7718 us |  107.4219 |   50.7813 |   3.9063 |  1202.38 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |             blogspot |     97.505 us |      4.7582 us |   0.2608 us |    9.1553 |    1.0986 |        - |     75.2 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |          codeproject |  1,795.484 us |     19.2379 us |   1.0545 us |  169.9219 |   85.9375 |        - |  1565.21 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                 ebay |  8,784.124 us |  3,282.1788 us | 179.9073 us |  546.8750 |  453.1250 |  93.7500 |  7360.78 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |         en.wikipedia | 20,083.330 us |  3,753.1019 us | 205.7202 us | 1093.7500 |  968.7500 |        - | 10436.21 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |               flickr |  5,419.500 us |  1,130.2417 us |  61.9524 us |  328.1250 |  226.5625 |  78.1250 |  6632.94 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |        florian-rappl |    436.828 us |     68.0346 us |   3.7292 us |   39.5508 |   10.7422 |        - |   323.52 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |              godaddy |      9.845 us |      1.8005 us |   0.0987 us |    1.6785 |    0.0305 |        - |    13.76 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |               google |  1,758.039 us |    401.8618 us |  22.0274 us |  117.1875 |   68.3594 |  42.9688 |  2889.62 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |           html5rocks |  1,903.009 us |    101.9915 us |   5.5905 us |  140.6250 |   70.3125 |        - |  1308.73 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |            html5test |    300.038 us |     42.2626 us |   2.3166 us |   35.6445 |    4.8828 |        - |   291.79 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |       huffingtonpost | 12,076.476 us |    820.9253 us |  44.9977 us |  734.3750 |  515.6250 |  31.2500 |  7985.22 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                 imdb | 12,498.418 us |  2,309.9129 us | 126.6141 us |  765.6250 |  625.0000 | 156.2500 |  11035.4 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |           kickass.to |      8.521 us |      3.6482 us |   0.2000 us |    1.4801 |    0.0305 |        - |    12.13 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |             linkedin |  2,381.911 us |     28.9987 us |   1.5895 us |  164.0625 |  156.2500 |        - |  1626.89 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                 live |     25.879 us |      0.4846 us |   0.0266 us |    2.6855 |    0.1221 |        - |    22.02 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |              mail.ru |  4,090.691 us |    751.3247 us |  41.1826 us |  296.8750 |  156.2500 |  15.6250 |  3794.44 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                  msn |    353.054 us |     29.3416 us |   1.6083 us |   61.5234 |   20.5078 |        - |   504.68 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |              myspace |  8,090.228 us |    881.1812 us |  48.3005 us |  562.5000 |  484.3750 |        - |  5077.31 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |                  nbc | 26,047.501 us | 17,699.3245 us | 970.1597 us | 1437.5000 | 1062.5000 | 187.5000 | 18108.22 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |               neobux |     89.080 us |      7.1386 us |   0.3913 us |    9.2773 |    1.2207 |        - |    76.41 KB |
|              |                      |               |                |             |           |           |          |             |
| AngleSharpOG |              netflix |    765.755 us |     19.4329 us |   1. [...]

2023-12-29 08:38 UTC, dv00d00 commented
I believe I'm done with all the changes I wanted to try, managed to reduce execution time by around 8% during last cpu optimization round, but most of optimisation I've tried did not yield any perf improvements, so this is a good place to stop atm.

2023-12-29 10:06 UTC, dv00d00 commented
Sorry for the huge size of this PR, I can split it into a few smaller ones if you prefer

2023-12-31 14:41 UTC, dv00d00 commented
Are there any outstanding tasks to complete on my end?

2024-01-01 12:13 UTC, FlorianRappl commented
> Are there any outstanding tasks to complete on my end?

No, before merging I'll set the `devel` branch to `1.1.0`. I think I will have time for the merge tomorrow or on Wednesday. Thanks for all the work - looks superb!

2024-01-02 09:20 UTC, dv00d00 commented
I am in the process of updating prod servers to this version (currently served from the local nuget feed), so will have some metrics data from the prod env before official release

2024-01-11 10:24 UTC, FlorianRappl approved these changes

2024-01-11 11:04 UTC, merged