New setting for disabling Stringbuilder pooling.
AngleSharp/AngleSharp pull request #1203
Opened 2024-09-23 17:01 UTC by micahbresette

# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [ ] I have read the **CONTRIBUTING** document
- [ ] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## Description

Added a new setting for disabling Stringbuilder pooling.  This can increase performance during heavy parallel processing as it will skip the lock.  However, by disabling pooling it can also increase overall memory consumption.

2024-09-23 17:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/AngleSharp/AngleSharp?pullRequest=1203) <br/>All committers have signed the CLA.

2024-09-24 07:21 UTC, FlorianRappl commented on src/AngleSharp/Text/StringBuilderPool.cs
> +        public static bool DisablePooling
Why not call it `IsPoolingDisabled`? Usually the `Is...` convention is used for boolean properties.

Plus we use the real type name and not the keyword / alias in the code base. (`bool` -> `Boolean`)

2024-09-24 07:21 UTC, FlorianRappl commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
Please put the original method lock body in an inlined method (e.g., `ObtainUnlocked`) -> then you can either call it from a `lock` or without the `lock` (depending on the condition).

2024-09-24 07:21 UTC, FlorianRappl commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
There is also a `_lock` in `ReturnToPool`, which should be taken (same strategy there). Otherwise, it's not consistent.

2024-09-24 07:21 UTC, FlorianRappl commented on src/AngleSharp/Text/StringBuilderPool.cs
> +        private static readonly Int32 _defaultStringBuilderSize = 1024;
Why is this a static readonly? Make it a const (it's not exposed and cannot be changed anyway -> a classic const).

2024-09-24 18:43 UTC, micahbresette commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
Thanks for pointing out the ReturnToPool, I was thinking about that one the earlier today.  As far as wrapping the original implementation in a separate method I don't think it will add any benefit, as we end up making it more complex by adding the additional checks and enabling the ability to mess up the logic by calling the internal method incorrectly (not in a lock, but saying get locked version).   There is not much code duplication (minus the creation of the actual string builder).  Maybe I am missing something here though.

2024-09-24 18:44 UTC, micahbresette commented on src/AngleSharp/Text/StringBuilderPool.cs
> +        private static readonly Int32 _defaultStringBuilderSize = 1024;
No reason it cannot be a const

2024-09-24 18:44 UTC, micahbresette commented on src/AngleSharp/Text/StringBuilderPool.cs
> +        public static bool DisablePooling
Updated

2024-09-26 15:10 UTC, micahbresette commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
I will mark as resolved for now.  @FlorianRappl please let me know your thoughts on the comment above and if its a blocker.

2024-09-27 06:55 UTC, FlorianRappl commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
Yeah we don't want to have such duplicates in there. These blocks should be 100% the same - so duplicating them does not feel right.

2024-09-27 15:14 UTC, micahbresette commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
So just to make sure I am understanding your ask correctly here.  You want an anonyn method that encapsuates the call to: 

```csharp
return new StringBuilder(1024);
```

2024-09-27 15:26 UTC, micahbresette commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
Done, let me know if you have any other suggestions @FlorianRappl

2024-09-27 15:47 UTC, FlorianRappl commented on src/AngleSharp/Text/StringBuilderPool.cs
>          public static StringBuilder Obtain()
Well, good that you ask - actually, you are right. I was under the wrong impression that both blocks have the same code. But they surely do not (we don't need to check if there is a builder pooled, as we assume that this was set from the beginning). So yes, the logic in both blocks (lock and non-lock) is different - especially in the return to pool.

Yeah let's keep it as is. Thanks for asking!

2024-09-27 22:45 UTC, FlorianRappl requested changes
Don't delete files - especially files that are used as test case inputs.

2024-09-30 15:54 UTC, micahbresette commented
> Don't delete files - especially files that are used as test case inputs.

@FlorianRappl That file is flagged as virus via windows defender.  My system deleted it.

2024-10-01 14:29 UTC, FlorianRappl approved these changes
LGTM - thanks!

2024-10-01 14:29 UTC, merged